# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read": "00_reading-data.ipynb"}

modules = ["utils.py"]

doc_url = "https://fligt.github.io/uplc2color/"

git_url = "https://github.com/fligt/uplc2color/tree/master/"

def custom_doc_links(name): return None
